### PR TITLE
Take set_order into account

### PR DESCRIPTION
**Pull request by BenjaminNavarro**
The `set_order` was not taken into account. This PR solves the issue

### CODE REVIEW

**Comment by greg-szabo** [comment]
Can this change be merged, please? I tested on my website, it works.

**Comment by greg-szabo** [comment]
Hi @BenjaminNavarro ! I forked the repository and added your commit to it, together with a few updates - including a security update to the jekyll-extract-element Ruby package.

You can find the updated code here: https://github.com/freshautomations/base-jekyll-template

The RubyGems version of that package uses an outdated and vulnerable version of the nokogiri package. I've added the source code into the theme instead, so it will always compile with the latest dependencies. (Less possibility of security vulnerabilities.)

I'm also planning to add a tutorial on how to use the theme in Jekyll.

**Comment by Robbie-Cook** [comment]
Hey @BenjaminNavarro , sorry about the incredibly long time.

Are you still keen to have this in? If so, I think we would want to change `set_order` to `order_number` for clarity. If it ends in `_number` it will show up in CloudCannon as a number field

**Comment by BenjaminNavarro** [comment]
@Robbie-Cook Sure, I rebased on master and made the change

**Review by Robbie-Cook — APPROVED** [review]
Awesome, looks great!

**Pull request merged**
